const API_URL = 'https://fortniteapi.io/v2/shop?lang=en';
const API_KEY = import.meta.env.VITE_API_KEY;

const example = {
  shop: [
    {
      mainId: 'Wheel_Precision_Bundle',
      displayName: 'Jayvyn Wheels',
      displayDescription: '',
      displayType: 'Item Bundle',
      mainType: 'bundle',
      offerId: 'v2:/d476e858b1f298296a859893187196ade64f80e1f70208ed5dc37b40f9b20a46',
      devName:
        '[VIRTUAL]1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn, 1 x Jayvyn for -1 MtxCurrency',
      webURL: '/item-shop/bundles/jayvyn-wheels-87fd067f',
      offerDates: {
        in: '2025-11-15T00:00:00.000Z',
        out: '2025-11-21T23:59:59.999Z',
      },
      colors: {
        color1: '#4B988D',
        color2: '#163631',
        color3: null,
        textBackgroundColor: '#163631',
      },
      displayAssets: [
        {
          displayAsset: 'DAv2_Bundle_Featured_Wheel_Precision',
          materialInstance: 'MI_0',
          primaryMode: 'MAX',
          productTag: 'Product.DelMar',
          url: 'https://media.fortniteapi.io/images/displayAssets/v2/MAX/DAv2_Bundle_Featured_Wheel_Precision/MI_0.png',
          flipbook: null,
          background_texture: null,
          background:
            'https://media.fortniteapi.io/images/shop/d476e858b1f298296a859893187196ade64f80e1f70208ed5dc37b40f9b20a46/v2/MI_0/background.png',
          full_background:
            'https://media.fortniteapi.io/images/shop/d476e858b1f298296a859893187196ade64f80e1f70208ed5dc37b40f9b20a46/v2/MI_0/info.en.png',
        },
      ],
      firstReleaseDate: '2024-09-18',
      previousReleaseDate: '2025-11-18',
      giftAllowed: true,
      buyAllowed: true,
      price: {
        regularPrice: 400,
        finalPrice: 400,
        floorPrice: 0,
      },
      rarity: {
        id: 'Common',
        name: 'COMMON',
      },
      series: null,
      banner: null,
      offerTag: {
        id: 'wheels',
        text: 'Includes wheel and wheel variants!',
      },
      granted: [
        {
          id: 'Wheel_Precision_None',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_Black',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_TitaniumWhite',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_Crimson',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_Cobalt',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_SkyBlue',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_BurntSienna',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_Saffron',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_Lime',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_ForestGreen',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
        {
          id: 'Wheel_Precision_Orange',
          type: {
            id: 'vehicle_cosmeticvariant',
            name: 'Style',
          },
          name: '',
          description: '',
          rarity: {
            id: 'Common',
            name: 'COMMON',
          },
          series: null,
          images: {
            icon: null,
            featured: null,
            background: null,
            icon_background: null,
            full_background: null,
          },
          juno: {
            icon: null,
          },
          beans: {
            icon: null,
          },
          video: null,
          audio: null,
          gameplayTags: [],
          set: null,
        },
      ],
      priority: -1,
      section: {
        id: 'JayvynIncantor.99',
        name: 'Vehicle Accessories',
        category: 'Start Your Engines',
        landingPriority: 0,
        metadata: null,
      },
      groupIndex: 0,
      storeName: 'BRWeeklyStorefront',
      tileSize: 'Size_1_x_1',
      categories: [],
    },
  ],
  result: true,
  nextRotation: null,
  currentRotation: {
    'PlatinumSeries.97': '2025-11-20 00:00:00+00:00',
    'BR1119.93': '2025-11-20 00:00:00+00:00',
    'TylerCreator.96': '2025-11-20 00:00:00+00:00',
    'BR1119.98': '2025-11-20 00:00:00+00:00',
    'PsychoBandit.97': '2025-11-20 00:00:00+00:00',
    'BR1119.95': '2025-11-20 00:00:00+00:00',
    'VictoryVibes1117.98': '2025-11-20 00:00:00+00:00',
    'SimpsonsBartLisaMoeTHEME.95': '2025-11-20 00:00:00+00:00',
    'Jamtracks11193910.99': '2025-11-20 00:00:00+00:00',
    'Jamtracks11193910.96': '2025-11-20 00:00:00+00:00',
    'SimpsonsBartLisaMoeTHEME.94': '2025-11-20 00:00:00+00:00',
    'Jamtracks11193910.97': '2025-11-20 00:00:00+00:00',
    'PsychoBandit.98': '2025-11-20 00:00:00+00:00',
    'JayvynIncantor.99': '2025-11-20 00:00:00+00:00',
    'SimpsonsBartLisaMoeTHEME.98': '2025-11-20 00:00:00+00:00',
    'TylerCreator.97': '2025-11-20 00:00:00+00:00',
    'SimpsonsBartLisaMoeTHEME.97': '2025-11-20 00:00:00+00:00',
    'BR1119.97': '2025-11-20 00:00:00+00:00',
    'TylerCreator.98': '2025-11-20 00:00:00+00:00',
    'PlatinumSeries.96': '2025-11-20 00:00:00+00:00',
    'PlatinumSeries.98': '2025-11-20 00:00:00+00:00',
    'BR1119.96': '2025-11-20 00:00:00+00:00',
    'BR1119.94': '2025-11-20 00:00:00+00:00',
    'SimpsonsBartLisaMoeTHEME.96': '2025-11-20 00:00:00+00:00',
    'Cybertruck.99': '2025-11-20 00:00:00+00:00',
    'Jamtracks11193910.98': '2025-11-20 00:00:00+00:00',
    'PsychoBandit.99': '2025-11-20 00:00:00+00:00',
    'HJDooganLocker.98': '2025-11-20 00:00:00+00:00',
    'TylerCreator.95': '2025-11-20 00:00:00+00:00',
    'SimpsonsBartLisaMoeTHEME.99': '2025-11-20 00:00:00+00:00',
    'HJDooganLocker.99': '2025-11-20 00:00:00+00:00',
    'BR1119.99': '2025-11-20 00:00:00+00:00',
    'PlatinumSeries.99': '2025-11-20 00:00:00+00:00',
    'VictoryVibes1117.99': '2025-11-20 00:00:00+00:00',
    'SideKicks1115.99': '2025-11-20 00:00:00+00:00',
    'WerewolfCar.99': '2025-11-20 00:00:00+00:00',
    'TylerCreator.99': '2025-11-20 00:00:00+00:00',
    'MercedesAMG.99': '2025-11-20 00:00:00+00:00',
    'SideKicks1115.98': '2025-11-20 00:00:00+00:00',
  },
  customBackground: null,
  fullShop: false,
  lastUpdate: {
    date: '2025-11-19 13:10:43+00:00',
    uid: '018b0dda3f74f8bcb4404ff42d95e00bc195a374',
  },
  specialOfferVideo: null,
};

export { API_URL, API_KEY };
